default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  sslmode: disable
  username: alphauser
  password: alphapassword

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
